language: node_js
node_js:
  - '10'

cache:
  - elm-stuff/build-artifacts
  - tests/elm-stuff/build-artifacts

install:
  - npm i -g npm@latest
  - npm install

script:
  - npm run build
  - mkdir it && cp -r !(it|node_modules|elm-stuff) it/ && cd it && npm i
  - npm run test:it
  - cd .. && rm -rf it

deploy:
  provider: surge
  skip_cleanup: true
