language: node_js
node_js:
  - 10.8

cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

install:
  - npm run build

defaults: &defaults
  script:
    - mkdir it && cp -r !(it|node_modules|elm-stuff) it/ && cd it && npm ci
    - npm run test:it
    - cd .. && rm -rf it

deploy: &deploy
  provider: surge
  skip_cleanup: true

jobs:
  include:
    - stage: integration tests
      <<: *defaults
    - stage: integration tests
      <<: *defaults
    - stage: integration tests
      <<: *defaults
    - stage: deploy
      name: 'Deploying to surge.sh'
      script: skip
      deploy: &surge
        provider: surge
        skip_cleanup: true
