language: node_js
node_js:
  - '8'

cache:
  - elm-stuff/build-artifacts
  - tests/elm-stuff/build-artifacts

install:
  - npm i -g npm@latest
  - npm i -g elm@0.19
  - npm i -g elm-test@0.19
  - npm install
  - travis_retry elm-package install --yes
  - cd tests && elm-package install --yes && cd ..

script:
  - npm run build
  - cd tests && elm-make --output=/dev/null --yes && cd ..
  - npm run test
  - mkdir it && cp -r !(it|node_modules|elm-stuff) it/ && cd it && npm i && elm-make --output=/dev/null --yes
  - npm run test:it
  - cd .. && rm -rf it

deploy:
  provider: surge
  skip_cleanup: true
