language: node_js
node_js:
  - 10.8

cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

defaults: &defaults
  script:
    - npm run build
    - mkdir it && cp -r !(it|node_modules|elm-stuff) it/ && cd it && npm ci
    - npm run test:it
    - cd .. && rm -rf it

jobs:
  include:
    - stage: integration tests
      <<: *defaults
    - stage: deploy
      name: 'Deploying to surge.sh'
      script:
        - npm run build
      deploy: &surge
        provider: surge
        skip_cleanup: true
