language: node_js
node_js:
  - 10.8

cache:
  directories:
    - node_modules
  override:
    - npm ci
    - npm run cy:verify

defaults: &defaults
  script:
    - npm run build
    - mkdir it && cp -r !(it|node_modules|elm-stuff) it/ && cd it && npm ci
    - npm run test:it
    - kill $(jobs -p) || true
    - cd .. && rm -rf it

jobs:
  include:
    - stage: test
      <<: *defaults
    - stage: test
      <<: *defaults
    - stage: test
      <<: *defaults

deploy:
  provider: surge
  skip_cleanup: true
