name: CI

on:
  push:

jobs:
  pr:
    name: Run tests on PR
    runs-on: ubuntu-latest
    env:
      CYPRESS_TOKEN: ${{ secrets.CYPRESS_RECORD_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Pre-install node
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: mkdir it && rsync -av --progress . it --exclude it --exclude node_modules --exclude elm-stuff --exclude .git && cd it
    - run: npm ci
    - run: npx cypress install
    - run: npm run test:it
    - run: cd .. && rm -rf it