name: CI

on:
  push:

jobs:
  pr:
    name: Run tests on PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pre-install node
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: dirs=$(find . -not \( -path ./node_modules -prune \) -not \( -path ./.idea -prune \))
    - run: mkdir it && cp $dirs it/ && cd it && npm ci
    - run: npm run test:it
    - run: cd .. && rm -rf it