name: CI

on:
  push:

jobs:
  pr:
    name: Run tests on PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pre-install node
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: mkdir it && cp -r "!(it|node_modules|elm-stuff)" it/ && cd it && npm ci
    - run: npm run test:it
    - run: cd .. && rm -rf it